VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

# KEYMAP_INTROSPECTION_ENABLE = no

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDES_ENABLE = yes
EXTRAKEY_ENABLE = yes
MAGIC_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes



RGBLIGHT_ENABLE = yes
VIALRGB_ENABLE = no
WS2812_DRIVER_REQUIRED = yes
OLED_ENABLE = yes
CAPS_WORD_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
SERIAL_DRIVER = vendor

RAW_ENABLE = yes
LTO_ENABLE = no
MOUSE_SHARED_EP = no
BOOTMAGIC_ENABLE = no


# SRC += quantum/color.c
# SRC += rgblight.c
# SRC += process_rgb.c
SRC += mouse_mode.c
SRC += tetris.c

